# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 43004d9be182149361b943196a413d3b351ae84c6ced87e369eff22f659c3fd6c7af23d74af13de8c5b82fa3ec2d5501cad2aef0a65bc25c3d8a6142949eb4f8

test:
  secret_key_base: e7211f88777e119e070eb01ebd5042118cd50d776e8a35668412f70eb014a3c7d94992142fc1773de59b1e319b76d27e787fb59db4b2644816568b067e3f39b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
